#Spring Web Properties
spring:
  banner:
    location: classpath:/bannerfile/banner.txt
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/mydb
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  error:  
    whitelabel:
      enabled: false
  
